install.packages("shiny", dependencies = TRUE)
install.packages("ggplot2", dependencies = TRUE)
install.packages("tidyr", dependencies = TRUE)
install.packages("maps", dependencies = TRUE)
install.packages("rlist", dependencies = TRUE)
install.packages("rgbif", dependencies = TRUE)
install.packages("RColorBrewer", dependencies = TRUE)