name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file dockerfile --tag timbosman-shiny:$(date +%s) --tag timbosman-shiny:latest

    - name: Run the Docker image
      run: docker run -id  -p 80:80 timbosman-shiny

    - name: Curl the Container
      run: curl http://127.0.0.1:80 -v
